config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :boats do
    resources :bookings, only: %i[new create edit update show]
    patch '/bookings/:id/update_false', to: 'bookings#update_false', as: 'update_false_booking'
  end
  resources :boat, only: [:destroy]
  get "/dashboard", to: "pages#show"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/boat.rb
class Boat < ApplicationRecord
  belongs_to :user

  has_many :bookings, dependent: :destroy
  has_one_attached :photo

  validates :address, presence: true
  validates :name, presence: true
  validates :category, presence: true
  validates :price, numericality: { greater_than: 0 }
  validates :capacity, numericality: { greater_than: 0 }

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :boat

  validates :start_date, presence: true
  validates :end_date, presence: true
end

app/models/user.rb
class User < ApplicationRecord

  has_many :bookings
  has_many :boats
  has_many :requested_bookings, through: :boats, source: :bookings

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :phone_number, presence: true, uniqueness: true
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :phone_number])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :phone_number])
  end
end

app/controllers/boats_controller.rb
class BoatsController < ApplicationController

  def index
    @boats = Boat.all
    if params[:query].present?
      @boats = Boat.near(params[:query])
    end

    @markers = @boats.geocoded.map do |boat|
      {
        lat: boat.latitude,
        lng: boat.longitude
      }
    end

  end

  def new
    @boat = Boat.new
  end

  def destroy
    @boat = Boat.find(params[:id])
    @boat.destroy
    redirect_to dashboard_path, status: :see_other
  end

  def create
    @user = current_user
    @boat = Boat.new(boat_params)
    @boat.user = @user
    if @boat.save
      redirect_to boat_path(@boat)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @boat = Boat.find(params[:id])
  end

  def update
    @boat = Boat.find(params[:id])
    @boat.update(boat_params)
    redirect_to boat_path(@boat)
  end

  def show
    @boat = Boat.find(params[:id])
    @markers = [
      {
        lat: @boat.latitude,
        lng: @boat.longitude
      }]
  end

  private

  def boat_params
    params.require(:boat).permit(:name, :category, :price, :capacity, :photo, :address)
  end

end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def new
    @boat = Boat.find(params[:boat_id])
    @booking = Booking.new
  end

  def show
    @booking = Booking.find(params[:boat_id])
  end

  def create
    @user = current_user
    @boat = Boat.find(params[:boat_id])
    @booking = Booking.new(booking_params)
    @booking.boat = @boat
    @booking.user = @user
    if @booking.save
      redirect_to root_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    booking = Booking.find(params[:id])
    booking.update(status: true)
    redirect_to dashboard_path
  end

  def update_false
    booking = Booking.find(params[:id])
    booking.update(status: false)
    redirect_to dashboard_path
  end

  def destroy
    @booking = Booking.new(booking_params)
    @booking.save
  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  def home
    @boats = Boat.all
  end
  def show
    @boats = current_user.boats
    @bookings = current_user.requested_bookings
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/boats/_form.html.erb
<div class="container">
  <%= simple_form_for @boat, url: boats_path, method: :post, local:true do |f| %>
    <%= f.input :name %>
    <%= f.input :category %>
    <%= f.input :price %>
    <%= f.input :capacity %>
    <%= f.input :photo, as: :file %>
    <%= f.input :address, label: "Address",
    input_html: {data: {address_autocomplete_target: "address"}, class: "d-none"},
    wrapper_html: {data: {controller: "address-autocomplete", address_autocomplete_api_key_value: ENV["MAPBOX_API_KEY"]}}%>
    <div>
      <%= f.submit "Create Boat" %>
    </div>
  <% end %>
</div>

<%# <div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
  </div>
</div> %>

app/views/boats/edit.html.erb
<%= render 'form', boat: @boat %>

app/views/boats/home.html.erb
<div class='container'>
  <div class='row'>
    <% @boats.each do |boat| %>
      <%= link_to boat, class: 'w-25 col-3 mb-5' do %>
        <div class="col card">
          <div class="card-body d-flex flex-column p-0">
            <img src="https://s2.qwant.com/thumbr/0x380/4/d/d48f20a46a4497747c29551c4b82ad98d3e32e6583072de5d795f0a0e3eb83/U77Profile_StbdQuarter.jpg?u=http%3A%2F%2Fww1.prweb.com%2Fprfiles%2F2014%2F06%2F19%2F11958824%2FU77Profile_StbdQuarter.jpg&q=0&b=1&p=0&a=0" class="card-img-top" alt="">
            <div class="card-text ps-3">
              <div class='d-flex gap-5 mt-1'>
                <p><%= boat.name %></p>
                <p><%= boat.category %></p>
              </div>
              <p id='avatar' style="position: absolute;right: 16px;top: 205px;"><%= boat.user_id %></p>
              <div class='d-flex justify-content-between pe-3 mt-4'>
                <p><%= boat.capacity %> <i class="fa-solid fa-people-group" style="color: #008000;"></i></p>
                <p><%= boat.price %> <i class="fa-solid fa-euro-sign" style="color: #008000;"></i></p>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/boats/index.html.erb
<div class='container'>
   <div class="row justify-content-center">
  <div class="col-sm-12 my-3">
    <%= form_with url: boats_path, method: :get, class: "d-flex p-5" do %>
      <%= text_field_tag :query,
            params[:query],
            class: "form-control",
            placeholder: "Type a new location"
        %>
      <%= submit_tag "Search", address: "", class: "btn btn-primary" %>
    <% end %>
<h2 style='color: white'>All Boats </h2>
  <div class='row'>
    <% @boats.each do |boat| %>
      <%= link_to boat, class: 'w-25 col-3 mb-5' do %>
        <div class="col card_boat">
          <div class="card-body d-flex flex-column p-0">
            <div class="card-img-top">
            <%= cl_image_tag boat.photo.key, height: 300, width: 280, crop: :fill %>
            </div>
            <div class="card-text ps-3">
              <div class='d-flex gap-5 mt-1'>
                <p><%= boat.name %></p>
                <p><%= boat.category %></p>
              </div>
              <div class='d-flex justify-content-between pe-3 mt-4'>
                <p><%= boat.capacity %> <i class="fa-solid fa-people-group" style="color: #008000;"></i></p>
                <p><%= boat.price %> <i class="fa-solid fa-euro-sign" style="color: #008000;"></i></p>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
<div style="width: 100%; height: 600px;"
  data-controller="map"
  data-map-markers-value="<%= @markers.to_json %>"
  data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"></div>
    </div>


<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
  </div>
</div>

app/views/boats/new.html.erb
<div class="mt-3 mb-3 w-25">
  <%= render 'form', boat: @boat%>
</div>
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
  </div>
</div>

app/views/boats/show.html.erb
<div class='container'>
    <h1 style='color: white'>Boat</h1>
  <div class="card-product d-flex mb-3 gap-3" id='my-boat-car'>
    <%= cl_image_tag @boat.photo.key, height: 300, width: 400, crop: :fill %>
    <div class="card-product-infos flex-column d-flex">
      <div class='flex-grow-1 pt-3'>
        <h2><%= @boat.user.first_name %> <%= @boat.user.last_name %>'s <%= @boat.name %></h2>
        <h3><%= @boat.category %></h3>
        <p><%= @boat.capacity %> seats</p>
        <p><%= @boat.address %></p>
        <h3 class="card-trip-pricing">£ <%= @boat.price %> </h3>
      </div>
    <div class='d-flex gap-3 mb-3'>
        <%= link_to "Book", new_boat_booking_path(@boat), class: 'btn-accept' %>
        <%= link_to "Back", boats_path, class: 'btn-decline' %>
    </div>
    </div>
  </div>




  <div style="width: 100%; height: 600px;"
    data-controller="map"
    data-map-markers-value="<%= @markers.to_json %>"
    data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"></div>

  <div class="footer">
    <div class="footer-links">
      <a href="#"><i class="fab fa-github"></i></a>
      <a href="#"><i class="fab fa-instagram"></i></a>
      <a href="#"><i class="fab fa-facebook"></i></a>
      <a href="#"><i class="fab fa-twitter"></i></a>
      <a href="#"><i class="fab fa-linkedin"></i></a>
    </div>
    <div class="footer-copyright">
    </div>
  </div>
</div>

app/views/bookings/edit.html.erb
<h1>Bookings#edit</h1>
<p>Find me in app/views/bookings/edit.html.erb</p>

app/views/bookings/index.html.erb
<h1>Bookings#index</h1>
<p>Find me in app/views/bookings/index.html.erb</p>

app/views/bookings/new.html.erb
<%= simple_form_for([@boat, @booking]) do |f| %>
  <div class="container mt-3 w-25">
    <h1 style='color: white'>Welcome</h1>
    <%= f.input :start_date,
    as: :string,
              input_html: { data: { controller: "datepicker" } } %>
    <%= f.input :end_date,
    as: :string,
              input_html: { data: { controller: "datepicker" } } %>
    <%= f.submit %>
<% end %>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        ...
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>
</div>

app/views/bookings/show.html.erb
<h1>Bookings#show</h1>
<p>Find me in app/views/bookings/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AirBoatAndBubble</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@100;300;400&display=swap" rel="stylesheet">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
    <link href="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.css" rel="stylesheet">
    <%= javascript_importmap_tags %>
  </head>

  <body class='blue'>
    <%= render "shared/navbar" %>
    <%= render "shared/flashes" %>
    <div >
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/_form.html.erb
<%# Ne sert actuellement à rien ='(
%>

<%= simple_form_for booking, url: boat_booking_url(booking.boat.id, booking.id), data: { "turbo-method": :delete }, remote: true do |f| %>
  <%= f.button :submit, 'Confirmer la réservation', class: 'btn btn-primary', data: { confirm: 'Êtes-vous sûr de vouloir confirmer cette réservation?' } %>
<% end %>

app/views/pages/home.html.erb
<div class='container'>

    <div class="header">
        <h1 class="title mt-3" style='color: white'>Welcome to the Air Boat & Bubble</h1>
        <h3 class="subtitle" style='color: white'>Our Best Boats</h3>
    </div>

    <div class="search-form row justify-content-center">
      <div class="col-sm-8 my-3">
        <%= form_with url: boats_path, method: :get, class: "d-flex p-5" do %>
          <%= text_field_tag :query,
                params[:query],
                class: "form-control",
                placeholder: "Type a Location"
            %>
          <%= submit_tag "Search", name: "", class: "btn btn-primary" %>
        <% end %>
      </div>
    </div>

    <div class='boat-list row'>
      <% @boats.sample(4).each do |boat| %>
        <%= link_to boat, class: 'w-25 col-3 mb-5 boat-card' do %>
          <div class="card">
            <div class="card-body d-flex flex-column p-0">
              <div class="card-image">
                <%= cl_image_tag boat.photo.key, height: 150, width: 200, crop: :fill %>
              </div>
              <div class='boat-info ps-3'>
                <div class='boat-name-category'>
                  <p><%= boat.name %></p>
                  <p><%= boat.category %></p>
                </div>
                <div class='boat-stats'>
                  <p><%= boat.capacity %> <i class="fa-solid fa-people-group" style="color: #008000;"></i></p>
                  <p><%= boat.price %> <i class="fa-solid fa-euro-sign" style="color: #008000;"></i></p>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>

</div>

  <footer class="footer">
    <div class="footer-links">
      <a href="#" aria-label="GitHub"><i class="fab fa-github"></i></a>
      <a href="#" aria-label="Instagram"><i class="fab fa-instagram"></i></a>
      <a href="#" aria-label="Facebook"><i class="fab fa-facebook"></i></a>
      <a href="#" aria-label="Twitter"><i class="fab fa-twitter"></i></a>
      <a href="#" aria-label="LinkedIn"><i class="fab fa-linkedin"></i></a>
    </div>
    <div class="footer-copyright">
      <!-- Copyright information goes here -->
    </div>
  </footer>

app/views/pages/show.html.erb
<div class="container">
  <div>
    <h3 class='mt-3' style='color: white;'>My boats :</h3>
    <div class="d-flex flex-wrap gap-3 mb-3 row justify-content-center">
      <% @boats.each do |boat| %>
        <div class="card d-flex flex-row col-3 my-3" id='my-boat-card'>
          <%= link_to boat_path(boat.id), class: 'w-100 text-decoration-none' do %>
            <%= boat.name %>
            <p> <%= boat.price %> € </p>
            <div class="d-flex flex-column align-items-center justify-content-center">
              <%= link_to "Edit", edit_boat_path(boat.id), class: 'text-decoration-none' %>
              <%= link_to "Delete", boat_path(boat), class: 'text-decoration-none',
                data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
    <div class="d-flex justify-content-center">
      <%= link_to 'Add a new boat', new_boat_path, class: "btn-accept" %>
    </div>
  </div>
  <div>
    <h3 style='color: white;'>Pending booking</h3>
    <div class='d-flex gap-5 pb-5'>
      <% @bookings.each do |booking| %>
        <% if booking.status == nil %>
          <div class='card mb-3', id='booking-card'>
            <div class="card-body d-flex flex-column mx-auto">
              <p>Applicant : <%= booking.user.first_name %></p>
              <p>Boat : <%= link_to booking.boat.name,  boat_path(booking.boat.id), class: 'text-decoration-none' %></p>
              <div>
                <p>From : <%= booking.start_date %></p>
                <p>To : <%= booking.end_date %></p>
              </div>
              <p>Status: <%= 'En attente' %></p>
              <div class='mx-auto'>
                <% if booking.status == nil %>
                  <%= link_to 'Accept', boat_booking_url(booking.boat.id, booking.id),
                    class: "btn-accept",
                    data: { turbo_confirm: 'Are you sure you want to accept this booking?', "turbo-method": :patch } %>
                  <%= link_to 'Decline', boat_update_false_booking_url(booking.boat.id, booking.id),
                    class: "btn-decline",
                    data: { turbo_confirm: 'Are you sure you want to decline this booking?', "turbo-method": :patch} %>
                <% elsif booking.status == false %>
                  <%= link_to 'Accept', boat_booking_url(booking.boat.id, booking.id),
                    class: "btn-accept",
                    data: { turbo_confirm: 'Are you sure you want to accept this booking?', "turbo-method": :patch } %>
                <% else %>
                  <%= link_to 'Decline', boat_update_false_booking_url(booking.boat.id, booking.id),
                    class: "btn-decline",
                    data: { turbo_confirm: 'Are you sure you want to decline this booking?', "turbo-method": :patch} %>
                <% end %>
              </div>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
  <div>
    <h3 style='color: white;'>Bookings replied</h3>
    <div class='d-flex gap-5 pb-5'>
      <% @bookings.each do |booking| %>
        <% if booking.status == false %>
          <% status = 'Declined' %>
        <% else %>
          <% status = 'Accepted' %>
        <% end %>
        <% if booking.status != nil %>
          <div class='card mb-3', id='booking-card'>
            <div class="card-body d-flex flex-column mx-auto">
              <p>Applicant : <%= booking.user.first_name %></p>
              <p>Boat : <%= link_to booking.boat.name,  boat_path(booking.boat.id), class: 'text-decoration-none' %></p>
              <div>
                <p>From : <%= booking.start_date %></p>
                <p>To : <%= booking.end_date %></p>
              </div>
              <p>Status: <%= status %></p>
              <div class='mx-auto'>
                <% if booking.status == false %>
                  <%= link_to 'Accept', boat_booking_url(booking.boat.id, booking.id),
                    class: "btn-accept",
                    data: { turbo_confirm: 'Are you sure you want to accept this booking?', "turbo-method": :patch } %>
                <% else %>
                  <%= link_to 'Decline', boat_update_false_booking_url(booking.boat.id, booking.id),
                    class: "btn-decline",
                    data: { turbo_confirm: 'Are you sure you want to decline this booking?', "turbo-method": :patch} %>
                <% end %>
              </div>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "logo.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", root_path, class: "nav-link" %>
          </li>
           <li class="nav-item active">
            <%= link_to "Boats", boats_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Dashboard", dashboard_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
          <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= image_tag "logo.png", class: "avatar", alt: "dropdown menu" %>
          </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>